version: "3.8"

services:
  # Backend Service (Deno App)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "2005:2005"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_URL: postgres://aios:soia@postgres:5432/aiom_db
      REDIS_URL: redis://redis:6379
    networks:
      - aios-network

  # PostgreSQL Service
  postgres:
    image: postgres:14-alpine
    container_name: aios-postgres-db
    environment:
      POSTGRES_USER: aios
      POSTGRES_PASSWORD: soia
      POSTGRES_DB: aiom_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - aios-network
    ports:
      - "6543:5432"

  # Redis Service
  # redis:
  #   image: redis:alpine
  #   container_name: aios-redis
  #   networks:
  #     - aios-network
  #   ports:
  #     - "6379:6379"

volumes:
  postgres-data:
  # redis-data:

networks:
  aios-network:
    driver: bridge
